#
# Docker compose file for testing - this assumes that:
#   - your config file is ./config.yaml
#   - your AWS credentials, if required, are at ${HOME}/.config/rssalertbot/credentials
#
version: "3"

services:
    rssalertbot:
        image: jwplayer/rssalertbot:latest
        build:
            context: .
            args:
                PIP_EXTRA_INDEX_URL: ${PIP_EXTRA_INDEX_URL}
        environment:
            AWS_CREDENTIAL_FILE: /home/bot/.aws/credentials
            AWS_PROFILE:         ${AWS_PROFILE:-dev}
            AWS_DEFAULT_REGION:  ${AWS_DEFAULT_REGION:-us-east-1}
        volumes:
            - ./config.yaml:/app/config.yaml
            - ${HOME}/.config/rssalertbot/credentials:/home/bot/.aws/credentials:ro
